package com.topicsbot.model.statistics;

/**
 * Author: Artem Voronov
 */
public enum CounterType {
  FLOOD,
  MESSAGES,
  WORDS,
  START_COMMAND,
  TOPICS_COMMAND,
  STATISTICS_COMMAND,
  ADD_TOPIC_COMMAND,
  WORLD_TOPICS_COMMAND,
  CANCEL_COMMAND,
  SETTINGS_COMMAND,
  HELP_COMMAND,
  RATE_COMMAND,
  RANK_COMMAND,
  DONATE_COMMAND
}
